name: build-and-lint

on:
  push:
    branches: ['ijjk/update-ci-workflow']

concurrency:
  group: ${{ github.ref }}-build-and-lint
  cancel-in-progress: true

env:
  NAPI_CLI_VERSION: 2.14.7
  TURBO_VERSION: 1.9.6
  RUST_TOOLCHAIN: nightly-2023-03-09
  PNPM_VERSION: 7.24.3
  NODE_MAINTENANCE_VERSION: 16
  NODE_LTS_VERSION: 18
  TEST_CONCURRENCY: 10
  # TODO: remove after testing
  # NEXT_TEST_CONTINUE_ON_ERROR: 'true'

jobs:
  build-and-lint:
    name: Build and Lint
    uses: vercel/next.js/.github/workflows/build_reusable.yml@ijjk/update-ci-workflow
    with:
      afterBuild: pnpm lint && apt install moreutils jq -y && ./scripts/check-examples.sh && ./scripts/check-pre-compiled.sh
    secrets: inherit

  testDev:
    strategy:
      fail-fast: false
      matrix:
        group: [1, 2, 3]
    needs: ['build-and-lint']

    uses: vercel/next.js/.github/workflows/build_reusable.yml@ijjk/update-ci-workflow
    with:
      afterBuild: NEXT_TEST_MODE=dev node run-tests.js --timings -g ${{ matrix.group }}/3 -c ${TEST_CONCURRENCY} --test-pattern '^(development|e2e|unit)/.*\.test\.(js|jsx|ts|tsx)$'
    secrets: inherit

  testProd:
    needs: ['build-and-lint', 'testDev']
    strategy:
      fail-fast: false
      matrix:
        group: [1, 2, 3]

    uses: vercel/next.js/.github/workflows/build_reusable.yml@ijjk/update-ci-workflow
    with:
      afterBuild: NEXT_TEST_MODE=start node run-tests.js --timings -g ${{ matrix.group }}/3 -c ${TEST_CONCURRENCY} --test-pattern '^(production|e2e)/.*\.test\.(js|jsx|ts|tsx)$'
    secrets: inherit

  testIntegration:
    needs: ['build-and-lint', 'testProd']
    strategy:
      fail-fast: false
      matrix:
        group: [1, 2, 3, 4, 5]

    uses: vercel/next.js/.github/workflows/build_reusable.yml@ijjk/update-ci-workflow
    with:
      afterBuild: node run-tests.js --timings -g ${{ matrix.group }}/5 -c ${TEST_CONCURRENCY} --test-pattern '^(integration)/.*\.test\.(js|jsx|ts|tsx)$'
    secrets: inherit

  testsPass:
    runs-on: [self-hosted, linux, x64]
    name: thank you, next
    needs: ['build-and-lint', 'testIntegration']
    steps:
      - run: echo 'success'
