on:
  push:
    branches: ['ijjk/update-ci-workflow']

name: Build, test, and deploy

env:
  NAPI_CLI_VERSION: 2.14.7
  TURBO_VERSION: 1.6.3
  RUST_TOOLCHAIN: nightly-2023-03-09
  PNPM_VERSION: 7.24.3
  NODE_MAINTENANCE_VERSION: 16
  NODE_LTS_VERSION: 18

jobs:
  build:
    runs-on: self-linux-x64-16gb

    env:
      TURBO_TEAM: 'vercel'
      TURBO_REMOTE_ONLY: 'true'
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}

    steps:
      - run: node -v

      - run: rustc --version

      - run: docker --version

      - run: pwd

      - uses: actions/checkout@v3
        with:
          fetch-depth: 25

      - run: fnm use 18

      - run: rustup toolchain install "${RUST_TOOLCHAIN}"

      - run: rustup default "${RUST_TOOLCHAIN}"

      - run: npm i -g "pnpm@${PNPM_VERSION}" "turbo@${TURBO_VERSION}" "@napi-rs/cli@${NAPI_CLI_VERSION}"

      - run: pnpm store path

      - run: pnpm install

      - run: pnpm build

      - run: turbo build-native -- --target x86_64-unknown-linux-gnu

      - run: pnpm playwright install-deps

      - run: pnpm playwright install chromium

      - run: git clean -xdf test; git checkout test;

      - run: node run-tests.js test/integration/production/test/index.test.js
