name: Test Production

on:
  push:
    branches: ['ijjk/update-ci-workflow']

concurrency:
  group: ${{ github.ref }}-test-prod
  cancel-in-progress: true

env:
  NAPI_CLI_VERSION: 2.14.7
  TURBO_VERSION: 1.6.3
  RUST_TOOLCHAIN: nightly-2023-03-09
  PNPM_VERSION: 7.24.3
  NODE_MAINTENANCE_VERSION: 16
  NODE_LTS_VERSION: 18
  TEST_CONCURRENCY: 10
  # TODO: remove after testing
  NEXT_TEST_CONTINUE_ON_ERROR: 'true'

  TURBO_TEAM: 'vercel'
  TURBO_REMOTE_ONLY: 'true'
  TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
  NEXT_TELEMETRY_DISABLED: 1

jobs:
  wait-build:
    runs-on: self-hosted-arm64-linux
    name: 'Wait build'
    steps:
      - uses: lewagon/wait-on-check-action@v1.3.1
        with:
          ref: ${{ github.ref }}
          check-name: 'build_initial / build'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          wait-interval: 10

  test:
    needs: ['wait-build']
    strategy:
      fail-fast: false
      matrix:
        group: [1, 2]

    uses: vercel/next.js/.github/workflows/build_reusable.yml@ijjk/update-ci-workflow
    secrets: inherit
    with:
      afterBuild: node run-tests.js --timings --type production -g ${{ matrix.group }}/2 -c ${TEST_CONCURRENCY} && NEXT_TEST_MODE=start node run-tests.js --timings --type e2e -g ${{ matrix.group }}/2 -c ${TEST_CONCURRENCY}
